### PR TITLE
ADD composer.json

### PR DESCRIPTION
**Pull request by michaelmeneses**

### CODE REVIEW

**Comment by davosmith** [comment]
No explanation given as to why I should want to add this file. Please link to Moodle docs explaining about use of composer files in Moodle plugins.

**Comment by michaelmeneses** [comment]
Hi @davosmith,

You can add **davosmith/moodle-block_objectives** as require in **MOODLE/composer.json**. Running the "composer update" command and COMPOSER (https://getcomposer.org/) will install the plugin in MOODLE/blocks/.

See my project at https://github.com/michaelmeneses/moodle-composer. Here we use ROOT/MOODLE/. So you do not have to change anything in Moodle, not even MOODLE/composer.json.

The composer.json file adds the minimum required to use it as a Moodle dependency. There is other information that can be incremented in the file that would not impact its operation as composer dependency.

Thank you.

**Comment by davosmith** [comment]
Again, please can you link to the pages in Moodle docs that describe the management of plugins via composer - once I've had a chance to compare your request to the official guidelines from Moodle HQ, I'll be more than happy to merge it in.

**Comment by michaelmeneses** [comment]
Hi,

Add composer.json will allow use PHP Composer to manage dependencies in Moodle.

This only will possible with composer.json.

See topic must recent: https://moodle.org/mod/forum/discuss.php?d=361703

**Pull request closed without merging**
